# places = [
#     'Aarni',
#     'Aasta',
#     'Abhona',
#     'Ahamadpur',
#     'Ahemednagar',
#     'Airoli',
#     'Ajanta',
#     'Ajmer',
#     'Ajmer Bus Stand',
#     'Ajmer Bus Stand',
#     'Ajmer Railway',
#     'Akluj',
#     'Akodiya',
#     'Akola',
#     'Akot',
#     'Akot',
#     'Akurdi, Pradhikaran',
#     'Alibaug',
#     'Allapalli',
#     'Amalner',
#     'Ambad',
#     'Ambegaon',
#     'Ambejogaie',
#     'Amravati',
#     'Andheri W',
#     'Andheri/Parle',
#     'Aurad',
#     'Aurangabad',
#     'Aurangabad',
#     'Aurangabad',
#     'Aurangabad',
#     'Ausa',
#     'Badnapur',
#     'Bali',
#     'Ballarpur',
#     'Balotra',
#     'Barali',
#     'Baramati',
#     'Baramati City',
#     'Barmer',
#     'Barmer',
#     'Barmer',
#     'Barmer',
#     'Barshi',
#     'Barshi/Paranda',
#     'Beawar',
#     'Beda',
#     'Beed',
#     'Bhadrawati',
#     'Bhandup',
#     'Bhandup / Vikroli',
#     'Bhatkeda',
#     'Bhayander',
#     'Bhigwan &Surrounding',
#     'Bhigwan Surrounding',
#     'Bhinmal',
#     'Bhiwandi',
#     'Bhiwandi',
#     'Bhokar',
#     'Bhokardan',
#     'Bhoom',
#     'Bhor',
#     'Bhor Interior',
#     'Bhosari',
#     'Bhosari,Midc',
#     'Bhuranpur',
#     'Bhusawal',
#     'Bibwewadi, Undri, Upper',
#     'Boda',
#     'Bodhwad',
#     'Boiser/Umroli',
#     'Buldana',
#     'Candbad',
#     'Canteen Suplier',
#     'Central Railway',
#     'Chakur',
#     'Chalisgaon',
#     'Chandrapur',
#     'Chandrapur',
#     'Chandrapur',
#     'Chandrapur',
#     'Chandrapur',
#     'Chincholi',
#     'Chincholi',
#     'Chinchwad',
#     'Chiplun',
#     'Chittorgarh',
#     'Dadar',
#     'Daund Local',
#     'Daund Rly',
#     'Deglur',
#     'Deola',
#     'Devni',
#     'Dhaiwadi',
#     'Dhalegaon',
#     'Dharangaon',
#     'Dharavi',
#     'Dharavi',
#     'Dharavi',
#     'Dharnii',
#     'Digha',
#     'Dindori',
#     'Diva',
#     'Docyard Road',
#     'Docyard Road',
#     'Docyard Road',
#     'Dombivali',
#     'Dondaicha',
#     'Falna',
#     'Fondshiras',
#     'Fulambri',
#     'Gachiroli',
#     'Gangapur',
#     'Gevraie',
#     'Ghansangvi',
#     'Ghatkopar East',
#     'Ghodap Dev',
#     'Ghodpeth',
#     'Gondpipri',
#     'Goregaon',
#     'Goregoan W',
#     'Govandi',
#     'Gudamalani',
#     'Guvaghar',
#     'Hadgaon',
#     'Harji',
#     'Himayatnagar',
#     'Hingoli',
#     'Ichawar',
#     'Indapur',
#     'Indore',
#     'Indore',
#     'Indore',
#     'Interior Area',
#     'Jadhavwadi, Chikhali',
#     'Jafrabad',
#     'Jaisalmer',
#     'Jalna',
#     'Jamkhed',
#     'Jeur',
#     'Jintur',
#     'Jogeshwari/Goregaon E',
#     'Jogeshwari/Malad W',
#     'Junnar',
#     'K.Bhima',
#     'Kahandwa',
#     'Kalamb',
#     'Kalewadi',
#     'Kalwa',
#     'Kalyan',
#     'Kalyan (E)',
#     'Kamathi Pura',
#     'Kamothe',
#     'Kannad',
#     'Karanja Lad',
#     'Karanja Lad',
#     'Karanji',
#     'Karjat',
#     'Katraj',
#     'Kawas',
#     'Kej',
#     'Khadki',
#     'Khamgaon',
#     'Khandala / Lonavala',
#     'Khar To Nsp Railway',
#     'Khed',
#     'Khed And Interior',
#     'Khed To Alephata',
#     'Khilchpur',
#     'Khilchpur',
#     'Khilchpur',
#     'Khilchpur',
#     'Khilchpur',
#     'Khknar',
#     'Khudus',
#     'Khutbav',
#     'Kinvat',
#     'Kolad',
#     'Kondwa',
#     'Koregaon',
#     'Korpana',
#     'Kurdwadi',
#     'Kurla East',
#     'Kurla East',
#     'Kurla Tilak Nager',
#     'Kurla West',
#     'Latur',
#     'Local',
#     'Local Satara',
#     'Loha & Naigaon',
#     'Lohagaon,Dhanori',
#     'Lonand',
#     'Lonar',
#     'Mahim To Dadar',
#     'Majalgaon',
#     'Maksi',
#     'Malegaon',
#     'Malegaon',
#     'Malegaon',
#     'Malkapur',
#     'Mands',
#     'Majalgaon',
#     'Maksi',
#     'Malegaon',
#     'Malegaon',
#     'Malegaon',
#     'Malkapur',
#     'Mandsore',
#     'Mangalvedha',
#     'Mangaon',
#     'Manmad',
#     'Manohanr Thana',
#     'Manoj Jain',
#     'Mantha',
#     'Manvat',
#     'Mapusa',
#     'Mehakar',
#     'Mira Rd',
#     'Mira Rd To Dahanu',
#     'Morgaon,Supa',
#     'Mukhed',
#     'Mulund',
#     'Mumbra',
#     'Naigaon',
#     'Nalasopara To Bandra',
#     'Nandafata',
#     'Nanded',
#     'Nanded Tal Interior',
#     'Nandura',
#     'Nandurbar',
#     'Nandurghat',
#     'Narangvadi',
#     'Nashik',
#     'Nashik',
#     'Nashik',
#     'Nashik',
#     'Nashik',
#     'Ner Dhule',
#     'Nerul',
#     'New Nanded',
#     'Nigdi, Mamurdi',
#     'Nimach',
#     'Nimgaon, Bavda',
#     'Nira',
#     'Nitoda',
#     'Nitur',
#     'Oni',
#     'Osmanabad',
#     'Paithan',
#     'Paithan',
#     'Palam',
#     'Pali',
#     'Panchincholi',
#     'Pandharpur',
#     'Pandharpur',
#     'Panvel',
#     'Parali',
#     'Paratwada',
#     'Parbhani',
#     'Partur',
#     'Pathri',
#     'Pcmc',
#     'Pednem',
#     'Pen',
#     'Peth Area.',
#     'Phaltan Interior',
#     'Phaltan Local',
#     'Phonda',
#     'Pusad',
#     'Rabale',
#     'Rahata',
#     'Rajgrh',
#     'Rajura',
#     'Ramesh',
#     'Rani',
#     'Rani',
#     'Rashin &Interior',
#     'Ratnagiri',
#     'Rey Road ',
#     'Rly Pune',
#     'Sadri',
#     'Sainathnagar, W.Sheri,',
#     'Sanchore',
#     'Sanderav',
#     'Sangam Nager',
#     'Sangola',
#     'Sanmeshwar',
#     'Saphale/Kelve',
#     'Satana',
#     'Savargaon',
#     'Sehore',
#     'Sehore',
#     'Serwa',
#     'Shahagad',
#     'Shegaon',
#     'Sheo',
#     'Sheoganj',
#     'Sheoganj',
#     'Shilphata',
#     'Shirpur',
#     'Shirval',
#     'Shriwardhan',
#     'Sikar',
#     'Sillod',
#     'Sindgaon',
#     'Sindhakhed Raja',
#     'Sindhri',
#     'Sinnar',
#     'Solapur',
#     'Solapur',
#     'Solapur Rail',
#     'Sumerpur',
#     'Swaroopganj',
#     'Tajpur',
#     'Talegaon',
#     'Talen',
#     'Taloja',
#     'Thane',
#     'Thane',
#     'Thane',
#     'Tirthpuri',
#     'Titwala',
#     'Tuljapur',
#     'Tuljapur',
#     'Udaipur',
#     'Udgir',
#     'Ujjain',
#     'Ujjain',
#     'Ulhasanagar',
#     'Ulhasanagar',
#     'Ulhasnagar',
#     'Ulhasnagar 4-5',
#     'Ulhasnagar/ Ambernath',
#     'Umarga',
#     'Umari',
#     'Urlikanchan',
#     'Vaijapur',
#     'Vairag',
#     'Vangani',
#     'Vasai(E) Nsp (W)',
#     'Vashi',
#     'Vashi',
#     'Vashi Naka',
#     'Wadala Truck Terminal',
#     'Wadala Truck Traminal',
#     'Wadsa',
#     'Waduj,Pusegaon',
#     'Wagholi, Ubalenagar',
#     'Wai City',
#     'Walgaon',
#     'Waluj',
#     'Warje, Uttamnagar, Malwadi',
#     'Warora',
#     'Warora',
#     'Washi',
#     'Wathar,Limb,Highway',
#     'Yevatmal',
#     'Yevatmal',
#     'Yevatmal',
#   ]

places = [
    'Aarni',
    'Aasta',
    'Abhona',
    'Ahamadpur',
]